---
# tasks file for mysql
- name: install python db tools
  yum: name={{item}} state=present update_cache=yes
  with_items:
    - MySQL-python

- name: install mariadb-server
  yum: name={{item}} state=present update_cache=yes
  with_items:
    - mariadb-server

# not required on centos
#- name: ensure listening on all interfaces
#  lineinfile: dest=/etc/my.cnf regexp=^bind-address
#              line="bind-address = 0.0.0.0"
#  notify: restart mariadb

# Always keep configuration changes before service commands in case of config errors
- name: ensure mariadb started
  service: name=mariadb state=started enabled=yes

- name: create demo schema
  mysql_db: name=demo state=present

- name: create demo user
  mysql_user: name=demo password=demo priv=demo.*:ALL host='%' state=present
