---
# tasks file for nginx
- name: install nginx
  yum: name={{item}} state=present update_cache=yes
  with_items:
    - nginx

- name: delete standard nginx.conf
  file: path=/etc/nginx/nginx.conf state=absent
  notify: restart nginx

- name: move new nginx.conf file
  copy: src=nginx.conf dest=/etc/nginx/nginx.conf mode=0755
  notify: restart nginx

- name: get active sites
  shell: ls -1 /etc/nginx/conf.d
  register: active_sites

- name: deactivate existing sites
  file: path="/etc/nginx/conf.d/{{ item }}" state=absent
  with_items: active_sites.stdout_lines
  when: item not in sites
  notify: restart nginx

- name: configure nginx site
  template: src=nginx.conf.j2 dest=/etc/nginx/conf.d/{{ item.key }}.conf mode=0755
  with_dict: sites
  notify: restart nginx

- name: ensure nginx is started
  service: name=nginx state=started enabled=yes
