---
- hosts: loadbalancers
  become: true
  tasks:
    - name: install nginx
      yum: name={{item}} state=present update_cache=yes
      with_items:
        - nginx

    - name: ensure nginx is started
      service: name=nginx state=started enabled=yes

    - name: delete standard nginx.conf
      file: path=/etc/nginx/nginx.conf state=absent
      notify: restart nginx

    - name: move new nginx.conf file
      copy: src=../../nginx/nginx.conf dest=/etc/nginx/nginx.conf mode=0755
      notify: restart nginx

    - name: configure nginx site
      template: src=../../templates/nginx.conf.j2 dest=/etc/nginx/conf.d/demo.conf mode=0755
      notify: restart nginx

  handlers:
    - name: restart nginx
      service: name=nginx state=restarted
