---
  - hosts: loadbalancers
    become: true
    tasks:
      - name: verify nginx service
        command: service nginx status

      - name: verify nginx listening on 80
        wait_for: port=80 timeout=2

  - hosts: webservers
    become: true
    tasks:
      - name: verify apache service
        command: service httpd status

      - name: verify apache listening on 80
        wait_for: port=80 timeout=2

  - hosts: databases
    become: true
    tasks:
      - name: verify mysql service
        command: service mariadb status

      - name: verify mysql listening on 3306
        wait_for: port=3306 timeout=2

  - hosts: ansible
    tasks:
      - name: verify end-to-end response
        uri: url=http://{{item}} return_content=yes
        with_items: groups.loadbalancers
        register: lb_index

      - fail: msg="index failed to return content"
        when: "'Hello, from sunny' not in item.content"
        with_items: "{{lb_index.results}}"


  - hosts: loadbalancers
    become: true
    tasks:
      - name: verify backend response
        uri: url=http://{{item}} return_content=yes
        with_items: groups.webservers
        register: web_index

      - fail: msg="index failed to return content"
        when: "'Hello, from sunny {{item.item}}' not in item.content"
        with_items: "{{web_index.results}}"
