---
  - hosts: loadbalancers
    become: true
    tasks:
      - name: verify nginx service
        command: service nginx status

      - name: verify nginx listening on 80
        wait_for: port=80 timeout=2

  - hosts: webservers
    become: true
    tasks:
      - name: verify apache service
        command: service httpd status

      - name: verify apache listening on 80
        wait_for: port=80 timeout=2

  - hosts: databases
    become: true
    tasks:
      - name: verify mysql service
        command: service mariadb status

      - name: verify mysql listening on 3306
        wait_for: port=3306 timeout=2
