---
- hosts: loadbalancers
  become: true
  name: Stop Loadbalancers
  tasks:
    - service: name=nginx state=stopped
    - wait_for: port=80 state=drained

- hosts: webservers
  become: true
  name: Stop Webservers
  tasks:
    - service: name=httpd state=stopped
    - wait_for: port=80 state=stopped

- hosts: databases
  become: true
  name: Restart DBs
  tasks:
    - service: name=mariadb state=restarted
    - wait_for: port=3306 state=started

- hosts: webservers
  become: true
  name: Start Webservers
  tasks:
    - service: name=httpd state=started
    - wait_for: port=80

- hosts: loadbalancers
  become: true
  name: Start Loadbalancers
  tasks:
    - service: name=nginx state=started
    - wait_for: port=80
